2023-06-01 14:48:00,752 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-01 14:48:14,227 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-01 14:48:30,126 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-01 14:48:47,998 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-01 14:50:01,475 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 16:13:32,391 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 16:17:40,755 ERROR: Exception on /sd/profile [GET] [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/routes.py", line 50, in profile
    if posts.has_next else None
AttributeError: 'list' object has no attribute 'has_next'
2023-06-03 16:32:54,411 ERROR: Exception on /sd/profile [GET] [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/routes.py", line 50, in profile
    if posts.has_next else None
AttributeError: 'list' object has no attribute 'has_next'
2023-06-03 16:36:36,460 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 16:36:51,350 ERROR: Exception on /sd/profile [GET] [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/routes.py", line 50, in profile
    if posts.has_next else None
AttributeError: 'list' object has no attribute 'has_next'
2023-06-03 16:43:11,053 ERROR: Exception on /sd/profile [GET] [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/routes.py", line 50, in profile
    prev_url = url_for('profile', username=user.username, page=posts.prev_num) \
AttributeError: 'list' object has no attribute 'has_next'
2023-06-03 16:43:15,179 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 16:46:23,332 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:32:05,244 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:33:12,858 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:36:04,834 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:36:50,837 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:37:24,471 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:37:43,945 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:38:37,911 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:39:48,978 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:40:16,120 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:40:40,759 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:41:18,275 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:41:57,057 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:42:31,826 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:45:06,384 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:49:41,254 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:51:38,364 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:54:26,116 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:54:47,734 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:55:56,199 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:57:25,145 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:57:35,426 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:58:07,504 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 17:58:19,608 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-03 18:01:58,439 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-07 12:35:13,852 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-07 12:37:07,071 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-07 12:37:39,461 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-07 13:00:56,360 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
2023-06-07 13:05:43,778 INFO: Tinker Full-stack App [in /mnt/c/Users/Administrator/Desktop/html/Chapter-12/app/__init__.py:48]
